##################################################
# USUARIOS
##################################################

### Registro de Usuario con sensor
POST http://localhost:8080/usuarios/registro
Content-Type: application/json

{
  "tieneSensor": true,
  "correo": "steffi.ryser.t@gmail.com",
  "contrasena": "Comelonmas1.",
  "nombre": "Steffi",
  "apellido": "Ryser",
  "fechaNacimiento": "2004-05-25",
  "telefono": "955523789",
  "rol": "diabetico",
  "tipo_diabetes": "1"
}

###

### Registro de Usuario sin sensor
POST http://192.168.100.4:3030/usuarios/registro
Content-Type: application/json

{
  "tieneSensor": false,
  "correo": "usuario.sin.sensor@gmail.com",
  "contrasena": "Comelonmas1.",
  "nombre": "Usuario",
  "apellido": "Normal",
  "fechaNacimiento": "1990-01-01",
  "telefono": "123456789",
  "rol": "diabetico",
  "tipo_diabetes": "1"
}

###

### Inicio de Sesión
POST http://192.168.100.4:3030/usuarios/inicio-sesion
Content-Type: application/json

{
  "correo": "usuario.sin.sensor@gmail.com",
  "contrasena": "Comelonmas1."
}

###

### Solicitar Restablecer Contraseña
POST http://localhost:8080/usuarios/solicitar-restablecer
Content-Type: application/json

{
  "correo": "itsuki.maki@gmail.com"
}

###

### Restablecer Contraseña
POST http://localhost:8080/usuarios/restablecer-contrasena
Content-Type: application/json

{
  "correo": "steffi.ryser.t@gmail.com",
  "token": "TOKEN_RESTABLECER",
  "nuevaContrasena": "NuevaContraseña123!"
}

###

##################################################
# CONFIGURACIÓN DE USUARIO
##################################################

### Configurar usuario
POST http://192.168.100.4:3030/config/26
Content-Type: application/json

{
  "hipo_min": 70,
  "normal_min": 80,
  "normal_max": 140,
  "hiper_max": 180,
  "frecuencia_medicion": 240,
  "notificaciones": 1,
  "zona_horaria": "America/Santiago",
  "idioma": "es"
}

###

### Obtener configuración
GET http://192.168.100.4:3030/config/26
###

##################################################
# NIVELES DE GLUCOSA
##################################################

### Registrar nivel de glucosa
POST http://192.168.100.4:3030/niveles-glucosa/ingesta
Content-Type: application/json

{
  "usuario_id": 26,
  "valor_glucosa": 190,
  "fecha_registro": "2025-01-19T15:30:00Z",
  "metodo_registro": "manual",
  "etiquetado": "ayuno",
  "notas": "prueba manual"
}

###
PUT http://192.168.100.4:3030/niveles-glucosa/editar/66
Content-Type: application/json

{
  "usuario_id": 26,
  "valor_glucosa": 240,
  "unidad": "mg/dL",
  "metodo_registro": "manual",
  "origen_sensor": null,
  "fecha_registro": "2025-01-12T09:00:00Z",
  "etiquetado": "ayuno",
  "notas": "Corrección"
}

###
DELETE http://192.168.100.4:3030/niveles-glucosa/eliminar/65
Content-Type: application/json

{
  "usuarioId": 25
}


###

### Iniciar monitoreo REAL
POST http://localhost:8080/niveles-glucosa/monitoreo/iniciar
Content-Type: application/json

{
  "usuarioId": 10,
  "intervalo": 300000
}

###

### Detener monitoreo REAL
POST http://localhost:8080/niveles-glucosa/monitoreo/detener
Content-Type: application/json

{
  "usuarioId": 10
}

###

### Obtener última lectura
GET http://localhost:8080/niveles-glucosa/monitoreo/ultima-lectura/
###

##################################################
# CONTACTOS DE APOYO
##################################################

### 1. Crear invitación
POST http://192.168.100.4:3030/contactos-apoyo/invitar
Content-Type: application/json

{
  "usuario_id": 26,
  "nombre_contacto": "Prueba 1",
  "email_contacto": "correo@ejemplo.com",
  "telefono_contacto": "+56944332211",
  "tipo_contacto": "familiar"
}

###

### 2. Redirección GET desde correo (simula clic del usuario)
GET http://192.168.100.4:3030/contactos-apoyo/aceptar/75836874-8094-4f1f-a37b-ee6262e0f767
###

### 3. Aceptar invitación (marca como aceptada)
POST http://192.168.100.4:3030/contactos-apoyo/aceptar/75836874-8094-4f1f-a37b-ee6262e0f767
Content-Type: application/json

###

### 4. Registro de usuario desde invitación
POST http://192.168.100.4:3030/usuarios/registro
Content-Type: application/json

{
  "tieneSensor": false,
  "correo": "juana.gomez.r@gmail.com",
  "contrasena": "Comelonmas1.",
  "nombre": "prueba 2",
  "apellido": "Gomez",
  "fechaNacimiento": "2004-05-25",
  "telefono": "955523789",
  "rol": "amigo",
  "token_invitacion": "75836874-8094-4f1f-a37b-ee6262e0f767"
}

###

### 5. Verificar si un contacto tiene permiso
GET http://localhost:8080/contactos-apoyo/verificar/10?contacto_usuario_id=16
###

### 6. Habilitar o deshabilitar un contacto
PATCH http://localhost:8080/contactos-apoyo/16/habilitar
Content-Type: application/json

{
  "habilitado": true
}

###

### 7. Cambiar prioridad del contacto
PATCH http://localhost:8080/contactos-apoyo/16/prioridad
Content-Type: application/json

{
  "prioridad": 1
}

###

### 8. Obtener mis contactos 
###
GET http://192.168.100.4:3030/contactos-apoyo/mis-contactos/26


### Editar contacto de apoyo
PUT http://192.168.100.4:3030/contactos-apoyo/mis-contactos/42
Content-Type: application/json

{
  "nombre_contacto": "Mariano Actualizado",
  "email_contacto": "mariano_editado@gmail.com",
  "telefono_contacto": "+56912345678",
  "tipo_contacto": "familiar",
  "prioridad": 2,
  "habilitado": 1
}

### Eliminar contacto de apoyo
DELETE http://192.168.100.4:3030/contactos-apoyo/mis-contactos/39

### Ver todas mis invitaciones enviadas
GET http://192.168.100.4:3030/contactos-apoyo/invitaciones/26


### Registrar token expo del usuario (NECESARIO PARA RECIBIR PUSH)
POST http://192.168.100.4:3030/api/notificaciones/registrar-token
Content-Type: application/json

{
  "usuario_id": 25,
  "expo_push_token": "ExponentPushToken[AQUI-TU-TOKEN]"
}

### Registrar glucosa manual
POST http://192.168.100.4:3030/api/glucosa
Content-Type: application/json

{
  "usuario_id": 25,
  "valor_glucosa": 280,
  "unidad": "mg/dL",
  "metodo_registro": "manual",
  "fecha_registro": "2025-01-01T12:00:00.000Z",
  "etiquetado": "antes_comida",
  "notas": "Prueba REST",
  "registrado_por": 1
}
